export const PACKAGE_NAME = "pi-tmux-subagents";
export const STATE_ENV = "PI_TMUX_SUBAGENTS_DIR";
export const SYSTEM_PROMPT_APPEND_ENV = "PI_TMUX_SUBAGENTS_SYSTEM_PROMPT_APPEND";
export const SYSTEM_PROMPT_APPEND_MAX_LENGTH = 8_192;
export const STATE_DIR_BASENAME = PACKAGE_NAME;
export const STATUS_KEY = PACKAGE_NAME;
export const TMUX_SESSION_PREFIX = `${PACKAGE_NAME}-`;
